#!/bin/bash
# If connecting first time send 'yes' on ssh's request.
# Expect must be installed on server. Options:
#  $1 - ssh address with parameters(if needed)
#
# Usage example:
#   ssh_yes "-p22 user@localhost"

ssh_yes() {
assword='
    "assword:" { %s }
    "$ "       { send "exit\n" }
'
[[ $2 ]] && pass="send \"$2\n\"" || pass="exit"
printf -v assword "$assword" "$pass"
expect <<  EOF
spawn  ssh $1
expect {
    "yes/no" {
        send "yes\n"
        expect { $assword }
    }
    $assword
}
EOF
}