#!/bin/bash
# If connecting first to server this will remove
# annoying question to add server to known_hosts
#
# Usage example:
#   ssh_yes 192.168.0.1 [/my/path/to/known_hosts|default is ~/.ssh/known_hosts]

ssh_yes() {
    local target=$1
    local knwhosts=${2:-~/.ssh/known_hosts}
    local fprint=($(ssh-keyscan -H "$target" 2>/dev/null))
    grep -q "${fprint[2]}" "$knwhosts" 2>/dev/null || echo "${fprint[@]}" >> "$knwhosts"
}